name: 'Heroku Deployment'
description: 'Deploy a specific commit to specified Heroku app'
inputs:
  heroku_app:
    required: true
    description: 'Name of Heroku app to deploy to, e.g. my-example-heroku-app'
  heroku_api_key:
    required: true
    description: 'Heroku API key'
  github_sha:
    required: false
    default: ${{ github.sha }}
    description: 'Commit hash, e.g. 59d2e89c36774ee3775050a437c290a6c1afb3db'
outputs:
  release_version:
    description: 'The release version of Heroku deployment, e.g. 10'

runs:
  using: "composite"
  steps:
    - run: python -m deploy_heroku
      shell: bash
    env:
      APP: ${{ inputs.heroku_app }}
      API_KEY: ${{ inputs.heroku_api_key }}
      COMMIT_HASH: ${{ inputs.github_sha }}
