name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: moneymeets/ruby-python-awscli:python3.8-poetry1.0-github

    steps:
      - uses: actions/checkout@v1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run linter
        run: poetry run flake8

      - name: Build and publish image
        run: |
          # Export requirements.txt to install dependencies into the docker image
          poetry export -f requirements.txt -o requirements.txt

          # For branch names other than master (e.g. feature/test), append last branch name component (test) to the tag
          export TAG=${GITHUB_REF##*/}
          docker build -t $DOCKER_REGISTRY:$TAG .

          if [ "$GITHUB_REF" == "refs/heads/master" ]; then docker tag $DOCKER_REGISTRY:$TAG $DOCKER_REGISTRY:latest ; fi

          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_REGISTRY

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: moneymeets/action-heroku-deploy
